### PR TITLE
Prepare for CRAN submission

### PR DESCRIPTION
**Pull request by peterhurford**

### CODE REVIEW

**Review by robertzk — APPROVED** [review]

**Comment by robertzk** [comment]
:shipit:

**Comment by peterhurford** [comment]
@robertzk I submitted to CRAN from this branch by running:

```
rr build
tar -zxvf recombinator_1.0.0.tar.gz
cd recombinator
rr check --strict
R
```

```R
devtools::build_win()
devtools::use_cran_comments()
devtools::submit_cran(".")
```

...I will make inevitable requested changes also in this branch and continue the CRAN process, and then merge this branch once the package is accepted to CRAN.

**Comment by peterhurford** [comment]
```R
install.packages("recombinator")
```

We're live! 👍

**Comment by robertzk** [comment]
Thanks @peterhurford !

**Pull request merged**
